"use client";
import { useMemo, useRef, useState } from "react";
import { Send, Sparkles, Brain, BookOpen } from "lucide-react";

type Msg={id:string;role:"user"|"assistant"|"system";content:string};
export default function ChatClient({character,conversationId,initialMessages}:{character:{id:string;name:string;tagline:string;avatarGradient:string};conversationId:string;initialMessages:Msg[]}){
 const [messages,setMessages]=useState(initialMessages); const [input,setInput]=useState(""); const [busy,setBusy]=useState(false); const bottom=useRef<HTMLDivElement>(null);
 const visible=useMemo(()=>messages.filter(m=>m.role!=="system"),[messages]);
 async function send(e:React.FormEvent){e.preventDefault();const text=input.trim();if(!text||busy)return;setInput("");setBusy(true);const user:Msg={id:crypto.randomUUID(),role:"user",content:text};const assistant:Msg={id:crypto.randomUUID(),role:"assistant",content:""};setMessages(m=>[...m,user,assistant]);
   try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({conversationId,message:text})});if(!r.ok)throw new Error(await r.text());const reader=r.body?.getReader();if(!reader)throw new Error('no stream');const dec=new TextDecoder();let acc='';while(true){const {done,value}=await reader.read();if(done)break;acc+=dec.decode(value,{stream:true});setMessages(m=>m.map(x=>x.id===assistant.id?{...x,content:acc}:x));bottom.current?.scrollIntoView({behavior:'smooth'});} }catch(err){setMessages(m=>m.map(x=>x.id===assistant.id?{...x,content:`오류: ${err instanceof Error?err.message:'unknown'}`}:x));}finally{setBusy(false);} }
 return <main className="mx-auto grid min-h-[calc(100vh-4rem)] max-w-7xl lg:grid-cols-[280px_1fr]"><aside className="hidden border-r border-white/5 p-6 lg:block"><div className={`h-40 rounded-3xl bg-gradient-to-br ${character.avatarGradient}`}/><h1 className="mt-5 text-xl font-medium">{character.name}</h1><p className="mt-1 text-sm leading-6 text-zinc-400">{character.tagline}</p><div className="mt-7 space-y-3 text-xs text-zinc-400"><div className="flex items-center gap-2"><BookOpen size={14} className="text-violet-400"/> Lorebook activation</div><div className="flex items-center gap-2"><Brain size={14} className="text-violet-400"/> Narrative + Zep memory</div><div className="flex items-center gap-2"><Sparkles size={14} className="text-violet-400"/> Inferaft model</div></div></aside><section className="flex min-h-[calc(100vh-4rem)] flex-col"><div className="flex-1 space-y-6 overflow-y-auto px-5 py-8 sm:px-10">{visible.map(m=><div key={m.id} className={m.role==='user'?'ml-auto max-w-2xl':'max-w-2xl'}><div className={m.role==='user'?'rounded-2xl rounded-tr-sm bg-violet-600 px-4 py-3 text-sm leading-7':'rounded-2xl rounded-tl-sm bg-zinc-900 px-4 py-3 text-sm leading-7 text-zinc-200'}>{m.content || (busy?'…':'')}</div></div>)}<div ref={bottom}/></div><div className="sticky bottom-0 border-t border-white/5 bg-zinc-950/90 p-4 backdrop-blur"><form onSubmit={send} className="mx-auto flex max-w-3xl items-end gap-3 rounded-2xl border border-white/10 bg-zinc-900 p-2"><textarea rows={1} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit();}}} placeholder={`${character.name}에게 메시지…`} className="max-h-40 min-h-11 flex-1 resize-none bg-transparent px-3 py-2 text-sm outline-none"/><button disabled={busy||!input.trim()} className="grid h-11 w-11 place-items-center rounded-xl bg-white text-black disabled:opacity-30"><Send size={17}/></button></form><p className="mt-2 text-center text-[11px] text-zinc-600">AI-generated fictional conversation · Enter to send · Shift+Enter for newline</p></div></section></main>;
}
